### ISSUE TITLE
example is not working

### ISSUE THREAD

**Issue by hdjeong80** [nabilkrs/youtube_downloader#2]
![Screenshot_20220415-180104](https://user-images.githubusercontent.com/54730048/163550790-4b817eca-7c6b-474c-b2e1-e690dc65fe81.jpg)

could you check this?

**Comment by nabilkrs** [comment]
hot reload makes a lot of requests on the server that hosts the entire code thus will cause Too Many Requests http issue. All you have to do is to complete coding your app then release it. It will work

**Comment by hdjeong80** [comment]
But your API doesn't even work with a web browser.

https://youtubedownloaderapii.herokuapp.com/?url=https://www.youtube.com/watch?v=yX0LzL9SHig&format=mp3&startTime=0&endTime=0

response: [{"error":""}]

**Comment by nabilkrs** [comment]
I just told you that hot reload makes a lot of request on the server thus will cause http issue. Anyway I'm working to solve that issue. Thank you for your patience.

**Comment by thivankasarathchandra** [comment]
Hi , I tested the example code with on a real device with release apk. still not working
